# Setup
title:        baka maker
tagline:      the simple game maker  
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       taoria
  url:        github.io/projectbaka-site

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown