# Setup
title:        baka maker
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       taoria
  url:        github.io/projectbaka-site

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown